version: 1.0.{build}
before_build:
- cmd: nuget restore Source/LinuxPackages.sln
build:
  project: Source/LinuxPackages.sln
  parallel: true
  verbosity: minimal
environment:
    COVERALLS_REPO_TOKEN:  
       secure: JZHWQcEI9LG2w8K0/7yH25IsGeGPy8DtBvuQSGVktriBkYaT8FdZInFE3kWHJ7QV
after_test:
  - cmd: Source\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:Source/Tests/LinuxPackages.Web.Mvc.Tests/bin/debug/LinuxPackages.Web.Mvc.Tests.dll /testcontainer:Source/Tests/LinuxPackages.Common.Tests/bin/debug/LinuxPackages.Common.Tests.dll" -output:coverage.xml
  - cmd: Source\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
