version: 1.0.{build}

before_build:
- cmd: nuget restore Source/LinuxPackages.sln

build:
  project: Source/LinuxPackages.sln
  parallel: true
  verbosity: minimal
  publish_wap: true

configuration: Release

environment:
  COVERALLS_REPO_TOKEN:  
    secure: JZHWQcEI9LG2w8K0/7yH25IsGeGPy8DtBvuQSGVktriBkYaT8FdZInFE3kWHJ7QV
  DefaultConnection-Web.config Connection String:
    secure: MJZ/JgYNbCFcF1PmHw5Xd7tHhlFsLfqExrEKEjzqwiNv+ci01qKihLv/datPisPzCjQwvOwEVCJ2JQ39iZbqS2Ql9RqVMnI+eKKgTSzoJuV4OuRShfWaiUdRMQm2Wu4CClZb6zD4VAScuf5zTf5/pmHg6snlqR6aLjDwfkmOksy8OdSXrCh6zv53KPx9sWXb       
       
after_test:
  - cmd: Source\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[LinuxPackages.*]* -[*.Tests]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:Source/Tests/LinuxPackages.Web.Mvc.Tests/bin/debug/LinuxPackages.Web.Mvc.Tests.dll /testcontainer:Source/Tests/LinuxPackages.Common.Tests/bin/debug/LinuxPackages.Common.Tests.dll" -output:coverage.xml
  - cmd: Source\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

deploy:
  - provider: WebDeploy
    server: https://linuxpackages.scm.azurewebsites.net:443/msdeploy.axd?site=linuxpackages
    website: linuxpackages
    username: $linuxpackages
    password:
      secure: g7eXYcfpsIkCBPDFioa8bwaVzwitRYHSRfyarHlRAgjk714BgFJt4xSUqH/cGq4xsb/yiJsDdiOHew4+7/Xi8w==
    ntlm: false
    remove_files: false
    app_offline: false
    skip_dirs: \\App_Data
    on:
      branch: master
